### ISSUE TITLE
Subtyping and typed function references

### ISSUE THREAD

**Issue by RossTate** [WebAssembly/function-references#25]
What is the plan for subtyping and typed function references?

**Comment by titzer** [comment]
There are at least three issues. 1.) Subtyping for validating value types, 2.) runtime type information for functions, and 3.) dynamic checks for indirect calls through tables.

1. I am not sure if there is something specific to `func.bind`, but there are currently test cases (e.g. https://github.com/WebAssembly/function-references/blob/master/test/core/func_bind.wast#L365) that enforce no subtyping between function references. I think this should be allowed. I've implemented the general thing, so I am failing tests now :(

2. Runtime type information?

3. Subtype checks for functions are expensive. Identity checks seem overly restrictive. (They also have their own issues--V8 does this with local canonicalization of signature ids and local views on tables, which allows separate compilation with no memory leaks, but makes table updates relatively expensive).

**Comment by rossberg** [comment]
@titzer, note the [discussion of function subtyping](https://github.com/WebAssembly/function-references/blob/master/proposals/function-references/Overview.md#possible-extension-function-subtyping) in the overview. I don't think we can afford to relax the existing call_indirect to allow subtyping, because that would cause a performance regression. Consequently, if we want function subtyping, we have to distinguish subtypable and non-subtypable function types (see the link).

We could then add a second form of call_indirect that operates up to subtyping, but I wonder what the use case would be, given that call_indirect is mostly wanted for compiling C/Rust, and other uses will probably prefer call_ref (potentially paired with casts).

**Comment by rossberg** [comment]
Subtyping on functions is not included in this proposal.
