### ISSUE TITLE
Are recursive types allowed?

### ISSUE THREAD

**Issue by tlively** [WebAssembly/function-references#41]
The overview mentions that subtyping is co-inductive, but it does not explicitly state that type section entries can reference later type section entries. If a reader were to extrapolate from Wasm's existing declarations-before-uses structure, they might arrive at the conclusion that type section entries cannot reference later type section entries and therefore recursive types are not allowed. Can we clarify this one way or another in the explainer?

**Comment by rossberg** [comment]
> extrapolate from Wasm's existing declarations-before-uses structure

Yeah, in fact, I want to change this to def-before-use for types in this proposal, in order to avoid the recursive types rabbit hole for now. But that requires a few structural changes to validation and instantiation, which I haven't gotten round to implementing yet.

(Aside: Note that the property you describe only applies to the binary format, not to the abstract syntax or text format, where everything is considered recursive.)

**Comment by rossberg** [comment]
Closing via #56.
