### ISSUE TITLE
Should we merge this proposal back into GC?

### ISSUE THREAD

**Issue by tlively** [WebAssembly/function-references#54]
With recent momentum on the GC proposal, it doesn't look like this proposal is likely to be shipped or used before the rest of GC. Since work implementing and using this proposal has so far been tied to broader work on GC, I think it would make sense to merge typed function references back into GC. Doing so would consolidate discussion in a single place and would save us the overhead of defining typed function references in one proposal and depending on them from another proposal.

**Comment by rossberg** [comment]
That would probably simplify my life. :) But there still is a conceptual difference, as typed function references are unrelated to GC and useful without, e.g., to avoid the runtime checks of call_indirect. That might show up, e.g., when discussing things like profiles. Even if we ship both proposals together, I hence see communicational/organisational value in keeping them separate.

**Comment by tlively** [comment]
Would it make sense to merge them for now and differentiate them again in the future (presumably after they've been merged to the spec) once there is a good reason to do so, e.g. when we define profiles?

**Comment by rossberg** [comment]
In theory, yes. But having done it a few times now, restructuring proposals is error-prone and _a lot_ of work, so back and forth is highly undesirable. I also have a hunch that keeping them separate helps better separation of concerns in the design.

**Comment by titzer** [comment]
I would support smashing them back together, because it feels like we really need to co-design them anyway. Practically speaking, the two proposal repos seem to get rebased at different times, so when the main spec gets updated, one might lag behind.

One scenario is see as being worrisome is that if we ship function references without GC, thinking that shipping GC is just around the corner, there could be a late design change that we'd like to make but can't because it would break function references which have shipped.

I also keep forgetting that GC depends on the type imports proposal. I am not sure if we should merge that in together, too.

Maybe we could do a trial merge of the two (or three) and see what it looks like? "Jumbo GC" if you will :-)

**Comment by tlively** [comment]
Good point about type imports as well. I would actually support keeping type imports separate and making them depend on GC rather than the other way around. At least on our side, we haven't needed type imports for anything so far and have no plans to spend time on them in the near future.

**Comment by rossberg** [comment]
FWIW, we already have other proposals depending on typed and/or func refs, but being independent of GC. For example, stack switching (I was about to rebase the stack switching repo onto funcrefs, in order to land an interpreter prototype). Type imports are unrelated to GC as well but assume typed refs. As do module linking and interface types. There might be more such features in the future.

If the only motivation is timing and consolidation of design, then I think we can handle that without entangling proposals. Would there be any benefit other than that?

**Comment by tlively** [comment]
No, I think the only motivation is the improved convenience of consolidating the proposals under the assumption that GC will ship before any of the other proposals that depend on typed function refs.

**Comment by titzer** [comment]
As per discussion in today's GC subgroup meeting, I'd be OK to keep this proposal separate and would be OK closing this issue.
